# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - production

pool:
  vmImage: ubuntu-latest
variables:
  - group: shared_variables
  - group: version_variables
  - name: app_version_name
    value: $(app_version_major).$(app_version_minor).$(app_version_patch)

name: $(app_version_major).$(app_version_minor).$(app_version_patch)+$(app_version_code)

jobs:
  - job: android_job
    displayName: Android job
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: setup_flutter.yml

      - task: DownloadSecureFile@1
        name: keyproperties
        displayName: Download key.properties file
        inputs:
          secureFile: "key.properties"

      - task: DownloadSecureFile@1
        name: keystore
        displayName: Download keystore file
        inputs:
          secureFile: "key.jks"

      - script: |
          cp $(keyproperties.secureFilePath) $(Build.SourcesDirectory)/android/key.properties
          cp $(keystore.secureFilePath) $(Build.SourcesDirectory)/android/app/key.jks

          echo Android folder contents: $(ls $(Build.SourcesDirectory)/android)
          echo App folder contents: $(ls $(Build.SourcesDirectory)/android/app)
        displayName: Copy keystore and key properties files

      - task: FlutterBuild@0
        displayName: Build flutter Android App
        inputs:
          target: "aab"
          projectDirectory: "."
          buildName: $(app_version_name)
          buildNumber: $(app_version_code)

      - task: CopyFiles@2
        inputs:
          Contents: "**/app-release.aab"
          TargetFolder: $(Build.ArtifactStagingDirectory)
          flattenFolders: true

      - task: PublishBuildArtifacts@1
        displayName: Publish Android Artifact
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)"
          ArtifactName: "Android"
