# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- production

pool:
  vmImage: ubuntu-latest
variables:
  flutterVersion: '3.24.4'
steps:
- task: FlutterInstall@0
  inputs:
    mode: 'auto'
    channel: 'stable'
    version: 'custom'
    customVersion: '3.24.4'
- script: |
    echo "Flutter version: $(flutterVersion)"
  displayName: "Debugging flutterVersion"
- script: |
    flutter doctor -v
  displayName: Runing flutter doctor
- script: |
    flutter pub get
  displayName: Running pub get  



- task: DownloadSecureFile@1
  name: keyproperties
  displayName: Download key.properties file
  inputs:
    secureFile: 'key.properties'

- task: DownloadSecureFile@1
  name: keystore
  displayName: Download keystore file
  inputs:
    secureFile: 'key.jks'

- script: |
      cp $(keyproperties.secureFilePath) $(Build.SourcesDirectory)/android/key.properties
      cp $(keystore.secureFilePath) $(Build.SourcesDirectory)/android/app/key.jks

      echo Android folder contents: $(ls $(Build.SourcesDirectory)/android)
      echo App folder contents: $(ls $(Build.SourcesDirectory)/android/app)
  displayName: Copy keystore and key properties files

- script: |
    flutter build appbundle --release
  displayName: "Building aab"