# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- production

pool:
  vmImage: ubuntu-latest
variables:
  group: shared_variables
steps:
- task: FlutterInstall@0
  displayName: "Installing flutter"
  inputs:
    mode: 'auto'
    channel: 'stable'
    version: 'custom'
    customVersion: 'latest'
- script: |
    flutter doctor -v
  displayName: Runing flutter doctor
- script: |
    flutter pub get
  displayName: Running pub get  